param(
  [string] $BuildRoot,
  [string] $OutputPath
)

$ErrorActionPreference = 'Stop'

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
$sourceDir = Join-Path $repoRoot 'tools\pico-universal-flash-nuke'
if (-not $BuildRoot) {
  $BuildRoot = Join-Path $repoRoot 'build\pico-universal-flash-nuke'
}
if (-not $OutputPath) {
  $OutputPath = Join-Path $repoRoot 'companion\firmware\pico-universal-flash-nuke.uf2'
}

$rp2040Build = Join-Path $BuildRoot 'rp2040'
$rp2350Build = Join-Path $BuildRoot 'rp2350'

function Invoke-Checked {
  param([string[]] $Command)
  & $Command[0] @($Command | Select-Object -Skip 1)
  if ($LASTEXITCODE -ne 0) {
    throw "Command failed with exit code ${LASTEXITCODE}: $($Command -join ' ')"
  }
}

function Get-Sha256Hex {
  param([string] $Path)

  $stream = [System.IO.File]::OpenRead($Path)
  try {
    $sha256 = [System.Security.Cryptography.SHA256]::Create()
    try {
      $bytes = $sha256.ComputeHash($stream)
      return [System.BitConverter]::ToString($bytes).Replace('-', '').ToLowerInvariant()
    } finally {
      $sha256.Dispose()
    }
  } finally {
    $stream.Dispose()
  }
}

Invoke-Checked @('cmake', '-S', $sourceDir, '-B', $rp2040Build, '-G', 'Ninja', '-DPICO_BOARD=pico', '-DCMAKE_BUILD_TYPE=Release')
Invoke-Checked @('cmake', '--build', $rp2040Build, '--target', 'flash_nuke')
Invoke-Checked @('cmake', '-S', $sourceDir, '-B', $rp2350Build, '-G', 'Ninja', '-DPICO_BOARD=pico2', '-DCMAKE_BUILD_TYPE=Release')
Invoke-Checked @('cmake', '--build', $rp2350Build, '--target', 'flash_nuke')

$rp2040Uf2 = Join-Path $rp2040Build 'flash_nuke.uf2'
$rp2350Uf2 = Join-Path $rp2350Build 'flash_nuke.uf2'
foreach ($uf2 in @($rp2040Uf2, $rp2350Uf2)) {
  if (-not (Test-Path -LiteralPath $uf2)) {
    throw "Expected UF2 was not produced: $uf2"
  }
}

$outputDir = Split-Path -Parent $OutputPath
New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
$out = [System.IO.File]::Open($OutputPath, [System.IO.FileMode]::Create, [System.IO.FileAccess]::Write)
try {
  foreach ($uf2 in @($rp2040Uf2, $rp2350Uf2)) {
    $in = [System.IO.File]::OpenRead($uf2)
    try {
      $in.CopyTo($out)
    } finally {
      $in.Dispose()
    }
  }
} finally {
  $out.Dispose()
}

$item = Get-Item -LiteralPath $OutputPath
$hashPath = "$OutputPath.sha256"
$hashLower = Get-Sha256Hex $OutputPath
Set-Content -LiteralPath $hashPath -Value "$hashLower  $($item.Name)" -Encoding ascii
$hashSourcePath = Join-Path $repoRoot 'companion\src\main\pico-universal-flash-nuke-hash.ts'
Set-Content -LiteralPath $hashSourcePath -Value @(
  '// Generated by tools/build-pico-universal-flash-nuke.ps1.'
  "export const PICO_UNIVERSAL_FLASH_NUKE_SHA256 = '$hashLower';"
  ''
) -Encoding ascii
Write-Host "Built $($item.FullName) ($($item.Length) bytes)"
Write-Host "Wrote $hashPath"
Write-Host "Wrote $hashSourcePath"
